name: Auto Current Affairs

on:
  schedule:
    - cron: "30 1 * * *"   # runs every day at 1:30 AM UTC
  workflow_dispatch:       # allows manual run


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install feedparser

      - run: python generate.py

      - run: |
          git config user.name "ca-bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "Daily CA update" || echo "No changes"
          git push
